uofgconnect/uofgconnect

connect/forms.py
connect/views.py
templates/connect/edit.html

Add profile editing

---

connect/models.py
connect/views.py
templates/connect/index.html

Summary of changes;
* Updated the UserProfile model to support map coordinates
* Updated  and fixed AJAX to perform HTTP POST and send coordinates to the view
* Updated the view to save the coordinates into the database

Add support for coordinates

---

connect/urls.py
connect/views.py
static/css/sidebar.css
static/js/main.js
templates/connect/base.html
templates/connect/index.html

Sidebar added to list all users registered.

Feature available users

---

connect/views.py
static/js/main.js
templates/connect/index.html

The sidebar shows only the online users based on the sessions.

Feature active users

---

static/js/main.js
templates/connect/index.html

You can now search users by name/surname in the sidebar.

Add user filtering in sidebar

---

connect/forms.py
connect/urls.py
connect/views.py
templates/connect/base.html
templates/connect/faq.html

Removed contact form. Add faq in the navbar and made all the questions & answers visible without having to collapse each one.

Fix categories

---

populate_connect.py

add database population script

---

templates/connect/base.html
templates/connect/landing.html

Removed image from landing page. Added information about the application.

Jumbotron to landing page

---

connect/views.py

Fixed the login to redirect to index instead of just rendering it. 
Made fixes to the uni news navbar. 
Other minor fixes.

fixed the login redirect and other minor things

---

connect/views.py
static/js/main.js
templates/connect/base.html
templates/connect/messages.html

Badge added with available notifications. Ajax request available to delete that specific notification in the backend.

Separate notifications

---

static/js/main.js
templates/connect/base.html
templates/connect/messages.html

Messages badge shows the number of messages except the ones accepted or rejected. Notification badge shows only the number of the ones accepted or rejected.

Fix badges

---

connect/views.py
templates/connect/faq.html
templates/connect/index.html

Refactoring  FAQ and map markers

---

connect/urls.py
connect/views.py
requirements.txt
static/js/main.js
templates/connect/base.html
templates/connect/index.html
templates/connect/messages.html
uofgconnect/settings.py

Added support for the ping implementation. Users can now contact their peers and send them meeting invitations. The peers can either accept or reject the invitation.

Add support for Ping messages

---

connect/views.py
templates/connect/index.html

The coordinates of all the online users become available. Superuser is excluded.

Fix the map coordinates

---

connect/tests/tests_about.py
connect/tests/tests_general.py
connect/tests/tests_index.py
connect/tests/tests_landing_page.py
connect/tests/tests_login.py
connect/tests/tests_messages.py
connect/tests/tests_registration.py

Added Django tests about the following:
* General cases
* About page
* Index page
* Landing page
* Messages page
* Registration
* Login

Add test suite for the application 

---

connect/tests/tests_index.py
connect/tests/tests_login.py
connect/tests/tests_messages.py
connect/tests/tests_registration.py
populate_script.py

Rename populate_coonect to populate_script

---

populate_script.py

updated the password in the populate script to itech

updated the password in the populate script

---

templates/connect/about.html
templates/connect/faq.html

Changed how icons are displayed in about page.

Changes in about page

---

static/js/main.js
templates/connect/base.html

In case no notifications are available, the dropdown doesn't open. Even when you dismiss the last notification the dropdown is automatically closed.

Zero notifications on dropdown

---

connect/forms.py
connect/tests/tests_about.py
connect/tests/tests_general.py
connect/tests/tests_index.py
connect/tests/tests_landing_page.py
connect/tests/tests_registration.py
connect/views.py
uofgconnect/urls.py

Summary of refactoring:
* added docstrings 
* added comments
* removed old debug prints
* removed unused imports
* removed unused variables

Backend refactoring

---

static/js/main.js
templates/connect/base.html
templates/connect/contact.html
templates/connect/edit.html
templates/connect/faq.html
templates/connect/index.html
templates/connect/landing.html
templates/connect/login.html
templates/connect/messages.html
templates/connect/register.html
templates/connect/uni_news.html

Comments to js functions added. Code alignment fixed.

Frontend refactoring
